//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaProductionDBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connexion
    {
        public long Identifiant { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<long> IdentifiantClient { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
