//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaProductionDBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metier
    {
        public Metier()
        {
            this.Offres = new HashSet<Offre>();
        }
    
        public long Identifiant { get; set; }
        public string Libelle { get; set; }
        public Nullable<long> IdentifiantDomaineMetier { get; set; }
    
        public virtual DomaineMetier DomaineMetier { get; set; }
        public virtual ICollection<Offre> Offres { get; set; }
    }
}
