//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaProductionDBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        public long Identifiant { get; set; }
        public string Intitule { get; set; }
        public string Reference { get; set; }
        public System.DateTime DatePublication { get; set; }
        public System.DateTime DateDebutContrat { get; set; }
        public int DureeDiffusion { get; set; }
        public int NbPostes { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfil { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<long> IdentifiantTypeContrat { get; set; }
        public Nullable<long> IdentifiantMetier { get; set; }
        public Nullable<long> IdentifiantDomaineMetier { get; set; }
        public Nullable<long> IdentifiantClient { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DomaineMetier DomaineMetier { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual TypeContrat TypeContrat { get; set; }
    }
}
