//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaProductionDBLIB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MegaCastingsEntities : DbContext
    {
        public MegaCastingsEntities()
            : base("name=MegaCastingsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Connexion> Connexions { get; set; }
        public virtual DbSet<DomaineMetier> DomaineMetiers { get; set; }
        public virtual DbSet<Metier> Metiers { get; set; }
        public virtual DbSet<Offre> Offres { get; set; }
        public virtual DbSet<Pack> Packs { get; set; }
        public virtual DbSet<TypeContrat> TypeContrats { get; set; }
    }
}
