//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaProductionDBLIB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pack
    {
        public Pack()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public long Identifiant { get; set; }
        public string Libelle { get; set; }
        public Nullable<double> Prix { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
